### PR TITLE
Server files

### PR DESCRIPTION
**Pull request by AsalaKM**
create server #4 #3

### CODE REVIEW

**Review by FarahZaqout — CHANGES_REQUESTED** [review]
Really good work, but again, split the server from the database please.

**Comment by FarahZaqout** [comment]
Also, make sure to write description in the pr and relate to the proper issue.

**Comment by AsalaKM** [comment]
ok I'll do that 🤗

**Review by FarahZaqout — CHANGES_REQUESTED** [review]
This is really good. Code is clean and really neat. But remove the empty files ```(helpers index and test.js)```.

Note: Router is a completely different logic from server. I will approve it in the same PR, but normally it should be pushed separately.

**Review by jema28 — APPROVED** [review]

**Review by SalwaMugh — APPROVED** [review]

**Pull request merged**
