### PR TITLE
Manager home

### PR DESCRIPTION
**Pull request by AsalaKM**
Add header & footer #10 
create homepage for manager #8

### CODE REVIEW

**Review by FarahZaqout — CHANGES_REQUESTED** [review]
Too many irrelevant files pushed.

Please only push files that have to do with the feature.

Server files should be pushed alone, so should database schema, and eslint.

**Comment by FarahZaqout** [comment]
Header and footer should be pushed in a different branch and pr than home page.

**Comment by AsalaKM** [comment]
this is mean I should separate it ?!

**Comment by FarahZaqout** [comment]
Yes

**Pull request closed without merging**
